#!/usr/bin/env node
/**
 * Sync IDL - ensures IDL has correct program address
 *
 * Anchor 0.32+ generates IDL automatically via `anchor build`.
 * This script just verifies the IDL exists and has the correct address.
 */

const fs = require('fs');
const path = require('path');

const JSON_IDL_PATH = 'target/idl/vouch_verifier.json';
const PROGRAM_ID = 'EhSkCuohWP8Sdfq6yHoKih6r2rsNoYYPZZSfpnyELuaD';

// Check if IDL exists (generated by anchor build)
if (!fs.existsSync(JSON_IDL_PATH)) {
  console.error(`IDL not found at ${JSON_IDL_PATH}. Run 'anchor build' first.`);
  process.exit(1);
}

// Read the IDL
let idl;
try {
  idl = JSON.parse(fs.readFileSync(JSON_IDL_PATH, 'utf8'));
} catch (e) {
  console.error('Could not parse IDL:', e.message);
  process.exit(1);
}

// Ensure address field is set
if (!idl.address) {
  idl.address = PROGRAM_ID;
  fs.writeFileSync(JSON_IDL_PATH, JSON.stringify(idl, null, 2));
  console.log(`Added address to IDL: ${PROGRAM_ID}`);
}

console.log(`IDL synced to ${JSON_IDL_PATH}`);
console.log(`Program ID: ${idl.address || PROGRAM_ID}`);
